name: Build APK

on:
  push:
    branches:
      - GAbuild
  pull_request:
    branches:
      - GAbuild
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'   # Must be specified
        java-version: '17'  # Use the required Java version
        java-package: 'jdk'       # Optional, default is 'jdk'
        architecture: 'x64'       # Optional
        check-latest: false       # Optional
  
    - name: Install Dependencies
      run: ./gradlew dependencies

    - name: Build APK
      run: ./gradlew assembleProductionVanillaOpenSourceDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/production/vanillaOpenSource/debug/*.apk  # Adjust the path as necessary
          
